
name: docsearch


on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

   
      - name: Get the content of docsearch.json as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat docsearch.json | jq -r tostring)"

      - name: Run algolia/docsearch-scraper image
        env:
          APPLICATION_ID: ${{ QERAK145PL }}
          API_KEY: ${{ d064a51cb72be021e935aa8e21d35042 }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
        run: |
          docker run \
            --env APPLICATION_ID=${QERAK145PL} \
            --env API_KEY=${d064a51cb72be021e935aa8e21d35042} \
            --env "CONFIG=${CONFIG}" \
            algolia/docsearch-scraper
